### ISSUE TITLE
Image upload with bad product data

### ISSUE THREAD

**Issue by ching-wang** [hughgrigg/ching-shop#44]
when an describe error come out, the changes/photos(things has been chosen/changed ) should be saved before error coming out.

**Comment by hughgrigg** [comment]
I think it might be better to separate the image upload from the product edit screen. That way you need to have a valid product before you do the photo upload, and the two won't clash with each other.

**Comment by ching-wang** [comment]
Good idea!

**Comment by hughgrigg** [comment]
Resolved by #87
